version: '3.8'
services:

  redis:
    container_name: flask_redis_base
    image: redis
    restart: always
    networks:
      celery_flask_net:
        ipv4_address: 172.169.169.2

  flask_app:
    container_name: flask_redis_main_app
    build: .
    ports:
        - "5000:5000"
    volumes:
        - .:/flask_app
    depends_on:
        - redis
    networks:
      celery_flask_net:
        ipv4_address: 172.169.169.1

networks:
  celery_flask_net:
    ipam:
      config:
        - subnet: 172.169.169.0/16